### ISSUE TITLE
Error installing pycairo in python 3.6

### ISSUE THREAD

**Issue by Thimxx** [pygobject/pycairo#104]
When trying to install pycairo in Windows I am getting the following error (apparently there is a file missing in distribution?):

C:\MYFOLDER\Python\Python36-32>python -m pip install pycairo
Collecting pycairo
  Using cached pycairo-1.16.3.tar.gz
Installing collected packages: pycairo
  Running setup.py install for pycairo ... error
    Complete output from command C:\UMYFOLDER\Python\Python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\MYFOLDER\\Local\\Temp\\pip-build-h97hsosd\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\MYFOLDER\Local\Temp\pip-wofzecat-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\cairo
    copying cairo\__init__.py -> build\lib.win32-3.6\cairo
    copying cairo\__init__.pyi -> build\lib.win32-3.6\cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\cairo
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=16 -DPYCAIRO_VERSION_MICRO=3 -IC:\MYFOLDER\Python\Python36-32\include -IC:\MYFOLDER\Python\Python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tccairo/device.c /Fobuild\temp.win32-3.6\Release\cairo/device.obj
    device.c
    c:\MYFOLDER\temp\pip-build-h97hsosd\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\MYFOLDER\Python\Python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\MYFOLDER\\Local\\Temp\\pip-build-h97hsosd\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\UMYFOLDER\Temp\pip-wofzecat-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\MYFOLDER\Temp\pip-build-h97hsosd\pycairo\

**Comment by lazka** [comment]
You need cairo and set LIB/INCLUDE accordingly as we don't provide Windows wheels yet.

You can try using https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo in the meantime.
