### ISSUE TITLE
Is it possible to create a template for invoices

### ISSUE THREAD

**Issue by Daniyal-Javani** [pygobject/pycairo#106]
Can I create some templates of invoices and populate them each time? Is that a good idea to use this module for invoices at all?
I want to use it in this project (it's an accounting software): https://github.com/Jooyeshgar/amir

**Comment by lazka** [comment]
pycairo is probably a bit too low level for this.

random suggestion: use jinja2 to create html and https://weasyprint.readthedocs.io/en/latest/index.html to convert to png/pdf

**Comment by stuaxo** [comment]
+1 

Other ways of creating pdfs, such as reportlab can be pretty painful, I've used a few of them and after the last time resolved to generate HTML and convert to PDF afterwards.

**Comment by Daniyal-Javani** [comment]
Yeah, I experienced that pain with reportlab!

**Comment by stuaxo** [comment]
Once is enough.

Mind you, in the really bad old days there was Java and XSLT, oh my !
