### ISSUE TITLE
Unable to use the C API from a C extension

### ISSUE THREAD

**Issue by P403n1x87** [pygobject/pycairo#110]
I must be doing something very silly, but I'm unable to build a C extension that makes use of the `pycairo` C API. If I use external symbols and link against `_cairo.*.so` then everything works fine, but with the C API, `gcc` produces weird machine code. The interpreter crashes when it gets to this point (just to show the kind of assembly generated; of course this bit of code means nothing on its own):

~~~ asm
 > │0x7ffff3b680f3 <Canvas_show+35> mov    rax,QWORD PTR ds:0x8                                                                                                                                                                 │
   │0x7ffff3b680fb <Canvas_show+43> ud2                                                                                                                                                                                         │
   │0x7ffff3b680fd                  add    BYTE PTR [rax],al                                                                                                                                                                    │
   │0x7ffff3b680ff                  add    BYTE PTR [rax-0x7d],cl                                                                                                                                                               │
   │0x7ffff3b68102 <_fini+2>        in     al,dx                                                                                                                                                                                │
   │0x7ffff3b68103 <_fini+3>        or     BYTE PTR [rax-0x7d],cl                                                                                                                                                               │
   │0x7ffff3b68106 <_fini+6>        (bad)                                                                                                                                                                                       │
   │0x7ffff3b68107 <_fini+7>        or     bl,al                                                                                                                                                                                │
   │0x7ffff3b68109                  add    BYTE PTR [rax],al                                                                                                                                                                    │
   │0x7ffff3b6810b                  add    BYTE PTR [rax],al                                                                                                                                                                    │
   │0x7ffff3b6810d                  add    BYTE PTR [rax],al                                                                                                                                                                    │
   │0x7ffff3b6810f                  add    BYTE PTR [rbx+0x61],ah                                                                                                                                                               │
   │0x7ffff3b68112                  imul   esi,DWORD PTR [rdx+0x6f],0x5041432e
~~~

(taken verbatim from `gdb`) which I cannot relate to any parts of my C code, since this should correspond to

~~~ C
  PyObject *args = Py_BuildValue("(O)", PycairoContext_FromContext(self->context, &PycairoContext_Type, NULL));
  for (running = 1; running;)
  {
    Canvas_on_draw(self, args, NULL);
    ...
  }
~~~

All that I'm doing is including the `pycairo.h` header file whenever I need some symbols from the `pycairo` module, and call `import_cairo` from `PyInit_x11` (I'm targeting Python 3)

~~~ c
PyMODINIT_FUNC
PyInit_x11(void)
{
  PyObject* m;

  if (PyType_Ready(&CanvasType) < 0)
    return NULL;

  m = PyModule_Create(&canvasmodule);
  if (m == NULL)
    return NULL;

  if (import_cairo() < 0)
    return NULL;

  Py_INCREF(&CanvasType);
  PyModule_AddObject(m, "Canvas", (PyObject *)&CanvasType);
  return m;
}
~~~

The import seems to go well since the problem happens after I instantiate an instance of `Canvas` (an object I'm defining in my extension), and I call the `show()` method (`Canvas_show`).

I've tried both a manual compilation/linking as well as the standard `distutil` solution, but they both produce the same machine code. Hence something weird must be happening when I import `pycairo.h` into my extension.

I'm sorry that I cannot provide the full source, but at the minute I only have a stub of the actual stuff that I will need at the end. Please let me know if you need more details to clarify the situation further.

**Comment by lazka** [comment]
No idea :/

**Comment by P403n1x87** [comment]
Is there a chance that the pycairo C API could be tested to rule out any issues with it? I would do it myself, but the example above is pretty much a minimal working example already.

**Comment by lazka** [comment]
pygobject runs it's test suite regularly against pycairo master and it uses the C API.

I'll have a look.

**Comment by P403n1x87** [comment]
I think I've narrowed it down to the following bit of code

~~~ C
PycairoContext_FromContext(self->context, &PycairoContext_Type, NULL)
~~~

Perhaps this is not the correct way to make use of the `PycairoContext_FromContext` macro?

**Comment by lazka** [comment]
It looks correct. Note that it takes the ownership of the context, maybe you are missing a `cairo_reference (self->context);`?

**Comment by P403n1x87** [comment]
I think I have found the problem, and it has nothing to do with `pycairo`. The offending line in the function

~~~ C
static PyObject *
Canvas_show(Canvas* self) {
  struct timespec ts = {self->interval / 1e9, self->interval % (int) 1e9};
  int running;

  // Input events
  XSelectInput(self->display, self->win_id, ButtonPressMask | KeyPressMask);
  XMapWindow(self->display, self->win_id);

  PyObject *cr = PycairoContext_FromContext(self->context, &(PycairoContext_Type), NULL);
  PyObject *args = Py_BuildValue("(O)", cr);
  for (running = 1; running;)
  {
    Canvas_on_draw(self, args, NULL);

    nanosleep(&ts, NULL);
    cairo_surface_flush(self->surface);

    switch (cairo_check_event(self->surface, 0)) {
    case 0xff1b:   // Esc
    case -1:       // left mouse button
      running = 0;
      break;
    }
  }

  Py_DECREF(args);
  cairo_destroy(self->context);
  cairo_surface_destroy(self->surface);
  XCloseDisplay(self->display);

  return Py_True;
}
~~~

was `  struct timespec ts = {self->interval / 1e9, self->interval % (int) 1e9};`. By casting 1e9 in the division fixes the _undefined behaviour_ issue:

~~~ C
  struct timespec ts = {self->interval / (int) 1e9, self->interval % (int) 1e9};
~~~

and all works as expected.

Thanks for your patience and assistance with this!

**Comment by P403n1x87** [comment]
`cairo_reference` doesn't seem to help. The moment my code uses, e.g. `Pycairo_CAPI->Context_Type` or  `PycairoContext_FromContext` from `pycairo.h` and the compilation looks like it is truncated.

**Comment by P403n1x87** [comment]
As expected, it turned out to be something extremely silly (to put it mildly). My code is split across two .c sources: `x11module.c`, which defines the module, and `canvas.c`. They both import `pycairo.h`, which means each translation unit will have its own local copy of `Pycairo_CAPI`. However, I was calling `import_cairo` only from `x11module.c` from `PyInit_x11`, as one is supposed to do.

The question is then: how do you use `pycairo`'s C APIs while keeping your source code modular? The workaround that I have found requires patching `pycairo.h` so that `Pycairo_CAPI_t *Pycairo_CAPI;` is in the `extern` class. Then define `Pycairo_CAPI_t *Pycairo_CAPI;` in `x11module.c` as a global variable, which will then be visible from `canvas.c`.

**Comment by lazka** [comment]
uh, thanks for figuring that out. I guess we will have to add a define to disable those things in the header.

**Comment by lazka** [comment]
pygobject handles it this way: https://gitlab.gnome.org/GNOME/pygobject/blob/c745866df9e4394c6615e79779fff1221a84953a/gi/pygobject.h#L225

**Comment by lazka** [comment]
I've added a C API test in #111 and a proposed fix for this currently building in #112

Feedback welcome

**Comment by P403n1x87** [comment]
Yep, looks good. That's pretty much what my code looks like now, after pre-processing.

Thanks for enhancing the `pycairo` C API! :)

**Comment by lazka** [comment]
thanks for checking :)

A release will follow shortly.

**Comment by lazka** [comment]
new release is out
