### ISSUE TITLE
PycairoContext_FromContext not available in pycairo 1.17.0

### ISSUE THREAD

**Issue by stuaxo** [pygobject/pycairo#113]
Shoebot has cairocffi support, with Gtk - so sometimes needs to use PycairoContext_FromContext.

With ```pycairo==1.16.3``` the code below works, but with 1.17.0 it appears PycairoContext_FromContext is not available any more =

```python
import ctypes
import cairo  # pycairo
import cairocffi

pycairo = ctypes.PyDLL(cairo._cairo.__file__)
pycairo.PycairoContext_FromContext.restype = ctypes.c_void_p
pycairo.PycairoContext_FromContext.argtypes = 3 * [ctypes.c_void_p]
ctypes.pythonapi.PyList_Append.argtypes = 2 * [ctypes.c_void_p]
```

**Comment by lazka** [comment]
Yeah, the private API is now hidden by default with gcc/clang as well.

See https://github.com/pygobject/pycairo/issues/59#issuecomment-316442034 for a solution.

**Comment by stuaxo** [comment]
Fantastic, I can see this is better.

I must've not had time to implement this before / somehow not seen this - real life has been intruding into free-time coding a lot these days :)
