### ISSUE TITLE
Ubuntu 18.04 installing by pip is broken

### ISSUE THREAD

**Issue by g--o** [pygobject/pycairo#117]
Had to install dependencies and to make the extension compile (being a little desperate) I had to apply the flag:
```
export CFLAGS="-I/usr/include/cairo $CFLAGS"
```

**Comment by stuaxo** [comment]
It looks like you have built cairo yourself, what output do you try building with the libcairo-dev packages instead ?

**Comment by lazka** [comment]
In theory `pkg-config --cflags-only-I cairo`, which we use to build things, should return the cairo include path.

**Comment by g--o** [comment]
@stuaxo Well I didn't set up the compilation myself exactly, the pip triggered the setup.py of the package which (after installing setuptools which wasn't pulled automatically for some reason) built cairo as shared library (cairo.so); I'm pretty much set up now, but I think you should look for ways to ease that process cause the library just wasn't included in the path. I did install the libcairo-dev package btw

At first I thought pip was too broken on 18.04 but then I installed other packages just fine.. I'm afraid I don't have the exact log anymore but if you've got more questions I can probably recall most problems I encountered

**Comment by g--o** [comment]
@lazka Interestingly enough lately I had some more problems with pkg-config, so it might be that it's just my PC. Maybe didn't install the dev packages correctly somehow.
I'd say for now it's safe to close the issue, but if anyone encounters this again I'd advise to make sure pkg-config is set correctly cause it'll bite back at some point.

**Comment by lazka** [comment]
ok
