### ISSUE TITLE
setup.py installs .pc files to wrong directories, and does not seem to provide override

### ISSUE THREAD

**Issue by mgorny** [pygobject/pycairo#119]
`setup.py` ends up installing .pc files into pretty random locations on our systems. Depending on the Python interpreter used, the locations used includes:
* `/usr/lib/pkgconfig` (instead of `lib64`) -- CPython,
* `/usr/lib-python/pkgconfig` -- PyPy.

Please provide an option to pass the correct path and override this broken automagic.

Original report: https://bugs.gentoo.org/664802

**Comment by lazka** [comment]
Yeah, since distutils doesn't deal with the lib directory we have to guess, it's currently something like:

```
python3 -c "import distutils.sysconfig, sys, os; print(os.path.dirname(distutils.sysconfig.get_python_lib(True, True, sys.prefix)))"
```

At least on Fedora, which also patches CPython to use lib64, this seems to work. I wonder what's different here.

**Comment by lazka** [comment]
Is this a new issue btw? The guessing code hasn't changed recently..

**Comment by mgorny** [comment]
No but we've stopped patching Python to force lib64 which made no sense. And as soon as somebody noticed things broke, I've looked closer and noticed it doesn't work with PyPy either.

**Comment by lazka** [comment]
ok, so you install python libs in /usr/lib and other libs in /usr/lib64 now?

**Comment by mgorny** [comment]
No, Python *libs* are in /usr/lib64. Only Python modules and extensions are in /usr/lib/python*.

**Comment by lazka** [comment]
I meant platform depended shared libraries (which I'd also call C-extensions, so I'm confused right now :D)

**Comment by mgorny** [comment]
```
$ qlist python:3.7 | grep lib64
/usr/lib64/libpython3.7m.so.1.0
/usr/lib64/libpython3.7m.so
/usr/lib64/pkgconfig/python-3.7.pc
/usr/lib64/pkgconfig/python-3.7m.pc
/usr/lib64/libpython3.7m.a
/usr/share/gdb/auto-load/usr/lib64/libpython3.7m.so.1.0-gdb.py
```

Everything else goes to /usr/lib (the upstream default).

**Comment by mgorny** [comment]
Gentle ping.
