### ISSUE TITLE
Question about cairocffi

### ISSUE THREAD

**Issue by nikolas** [pygobject/pycairo#123]
The readme says:

> If Pycairo is not what you need, have a look at cairocffi

In what situations would I need cairocffi instead of pycairo? I think this could be written a little clearer.

**Comment by lazka** [comment]
That was written at a time where pycairo didn't have PyPy support, so that was the main difference back then. Now that we do support PyPy the difference is probably higher performance with PyPy (but there haven't been any benchmarks)
