### ISSUE TITLE
Local id in url handled incorrectly

### ISSUE THREAD

**Issue by Tezar** [pygobject/pycairo#133]
When url in property refers to local id, pycairo still interprets it as local file. Minimal example bellow. Shows correctly at least in Inkscape/Firefox/Chrom/IE. `cairosvg` fails with `#clipCircle` not found.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="500" height="500" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <clipPath id="clipCircle">
      <circle style="opacity:1;fill:#ffffff;fill-opacity:1;"
         cx="250"
         cy="250"
         r="250" />
    </clipPath>
  </defs>
  <rect
     style="opacity:1;fill:#000000;"
     width="500" height="300"
     x="0" y="100"
     clip-path="url(#clipCircle)"
  />
</svg>
```
Inkscape generates equivalent code. 
According to my understanding of specs, this should be ok.

**Comment by lazka** [comment]
Can you report this to cairo? pycairo only implements the Python bindings.

**Comment by lazka** [comment]
-> https://gitlab.freedesktop.org/groups/cairo/-/issues
