### ISSUE TITLE
Installing pygobject and pycairo on cygwin 

### ISSUE THREAD

**Issue by E3V3A** [pygobject/pycairo#135]
Background:

Trying to update `pygobject` on python3 under *Cygwin*. 

NOTE: Before dismissing Cygwin, please recall it's Fedora based and many of the Fedora packages/libraries have been ported. Almost anything works, except native Windows GUI (MinGW/VS) stuff.

After having looked at too many relevant and irrelevant links, I now understand there are significant work being done to address the issues of not being able to do simple and relaibale `pip install` on packages relying on *cairo, pygobjects, cffi* and what not. 

**I do understand** that this may not be the right place to post this, but then again I don't know where would be the right place. The issues are interconnected so I guess it's better to just post where the developers are. Which bring up another question. Why is **pygobject** being developed on GitLab [GNOME](https://gitlab.gnome.org/GNOME/pygobject) and not on github, while **pycairo** is here?

This is what I have:

```bash
# pip3 list --outdated
Package      Version       Latest Type
------------ ------------- ------ -----
pygobject    3.26.1        3.30.1 sdist

# cygcheck.exe -c |grep Incomplete
python3-asn1crypto                       0.22.0-1                  Incomplete
python3-cairo                            1.12.0-1                  Incomplete
python3-idna                             2.5-1                     Incomplete
python3-lxml                             3.7.3-1                   Incomplete
python3-numpy                            1.11.2-1                  Incomplete
python3-packaging                        16.8-1                    Incomplete
python3-ply                              3.9-1                     Incomplete
python3-pyparsing                        2.1.10-1                  Incomplete
python3-setuptools                       34.3.2-1                  Incomplete

# pipversions_of_incomplete_cyg_packs.sh

asn1crypto          0.24.0
pycairo             1.18.0
idna                2.7
lxml                4.2.5
numpy               1.15.4
packaging           18.0
ply                 3.11
pyparsing           2.3.0
setuptools          40.5.0


# pip3 list |grep setuptools
setuptools          40.5.0

# python3 -c 'import setuptools as s; print("%s\n%s" % (s.__path__, s.__version__))'
['/usr/lib/python3.6/site-packages/setuptools']
40.5.0
```
WHERE:  `"Incomplete"`, give cygwin packages that have been overridden by python3 pip

---

This is what I get:
 
```bash
# pip3 install --no-cache-dir pygobject
Requirement already satisfied: pygobject in /usr/lib/python3.6/site-packages (3.26.1)

# pip3 install --no-cache-dir pygobject -U
Collecting pygobject
  Downloading https://files.pythonhosted.org/packages/00/17/198a9d0eb0e89b5c7d2a9b4437eb40d62702ab771030cd79fc7141cb0d30/PyGObject-3.30.1.tar.gz (711kB)
    100% |████████████████████████████████| 716kB 5.3MB/s
Requirement already satisfied, skipping upgrade: pycairo>=1.11.1 in /usr/lib/python3.6/site-packages (from pygobject) (1.18.0)
Installing collected packages: pygobject
  Found existing installation: pygobject 3.26.1
Cannot uninstall 'pygobject'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

```

BTW. All this started when trying to install `bcrypt` which seem to depend on *cffi*, but installing/updating cffi depend on Cairo which refuse to build... 
:face_with_head_bandage:

**Comment by E3V3A** [comment]
PS.  I also have: 
```bash
# cygcheck.exe -c |grep -i cairo
libcairo-devel                           1.14.12-1                 OK
libcairo2                                1.14.12-1                 OK
mingw64-x86_64-cairo                     1.14.12-1                 OK
python3-cairo                            1.12.0-1                  Incomplete
python3-cairo-devel                      1.12.0-1                  OK

# pip3 list |grep -i cairo
pycairo             1.18.0

```

**Comment by lazka** [comment]
Can you try "pip3 install --user". It should install things into your home dir without writing stuff too your "system" dir.

> Why is pygobject being developed on GitLab GNOME and not on github, while pycairo is here?

Because at the time pycairo moved to github there was no GNOME gitlab.

**Comment by E3V3A** [comment]
@lazka 
Hi Christoph,
Thanks for quick response. I have since made a complete re-install of many libraries, to rule out dependency errors etc. So I'm working on getting it all back together. I'll report back as soon as I got it back up.

**Comment by lazka** [comment]
If you have any new info please post here or open a new issue. I'm closing this for now.
