### ISSUE TITLE
Sustainability of Travis and what to move to instead? 

### ISSUE THREAD

**Issue by stuaxo** [pygobject/pycairo#141]
I don't have the link to hand, but if you look on twitter, the company that took over Travis has been letting go of a lot of staff.

Its probably worth considering moving off Travis, what are the options?

**Comment by lazka** [comment]
We could move more things to azure pipelines if needed, but that will lose us performance because of the parallel job limit.

I kinda doubt that twitter talk is a good indicator re the state of the company.

**Comment by stuaxo** [comment]
https://mobile.twitter.com/ReinH/status/1098663375985229825

**Comment by stuaxo** [comment]
Didnt see your reply before posting that, you're right, may as well wait and see if anything changes.
