### ISSUE TITLE
libffi requirement not found on installation

### ISSUE THREAD

**Issue by loftusa** [pygobject/pycairo#142]
Hey, running into some installation problems with `pip install pycairo`:

Gonna work to fix it, but thought I should throw this on here as this is what I got on first install (already did `brew install cairo`, and that is on my computer).

Cheers.

`
(env) alex$ pip install pycairo
Collecting pycairo
  Using cached https://files.pythonhosted.org/packages/a6/54/23d6cf3e8d8f1eb30e0e58f171b6f62b2ea75c024935492373639a1a08e4/pycairo-1.18.0.tar.gz
Building wheels for collected packages: pycairo
  Building wheel for pycairo (setup.py) ... error
  Complete output from command /Users/alex/Dropbox/Programming/Projects/manim/env/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jk/j561y4wx4gs5b5l9pgdt7n6m0000gn/T/pip-install-xo1vr_v0/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/jk/j561y4wx4gs5b5l9pgdt7n6m0000gn/T/pip-wheel-ibw1p5nk --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/cairo
  copying cairo/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/cairo
  copying cairo/__init__.pyi -> build/lib.macosx-10.14-x86_64-3.7/cairo
  copying cairo/py.typed -> build/lib.macosx-10.14-x86_64-3.7/cairo
  running build_ext
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'libffi', required by 'gobject-2.0', not found
  Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.

  ----------------------------------------
  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pycairo
Installing collected packages: pycairo
  Running setup.py install for pycairo ... error
    Complete output from command /Users/alex/Dropbox/Programming/Projects/manim/env/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jk/j561y4wx4gs5b5l9pgdt7n6m0000gn/T/pip-install-xo1vr_v0/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jk/j561y4wx4gs5b5l9pgdt7n6m0000gn/T/pip-record-qy9ngmxh/install-record.txt --single-version-externally-managed --compile --install-headers /Users/alex/Dropbox/Programming/Projects/manim/env/bin/../include/site/python3.7/pycairo:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/cairo
    copying cairo/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/cairo
    copying cairo/__init__.pyi -> build/lib.macosx-10.14-x86_64-3.7/cairo
    copying cairo/py.typed -> build/lib.macosx-10.14-x86_64-3.7/cairo
    running build_ext
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'gobject-2.0', not found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.

    ----------------------------------------
Command "/Users/alex/Dropbox/Programming/Projects/manim/env/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jk/j561y4wx4gs5b5l9pgdt7n6m0000gn/T/pip-install-xo1vr_v0/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jk/j561y4wx4gs5b5l9pgdt7n6m0000gn/T/pip-record-qy9ngmxh/install-record.txt --single-version-externally-managed --compile --install-headers /Users/alex/Dropbox/Programming/Projects/manim/env/bin/../include/site/python3.7/pycairo" failed with error code 1 in /private/var/folders/jk/j561y4wx4gs5b5l9pgdt7n6m0000gn/T/pip-install-xo1vr_v0/pycairo/
`

**Comment by loftusa** [comment]
Update: It's a pretty simple fix ... upon `brew install libffi`, you get:

```
libffi is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/usr/local/opt/libffi/lib"

For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
```

and, after running both of those exports `pip install pycairo` works fine.
But, this currently has to be done manually, as far as I can tell.

**Comment by lazka** [comment]
yeah, I don't know why homebrew libffi doesn't install a .pc file like everyone else. Feel free to ask them ;)

**Comment by loftusa** [comment]
@lazka Yeah, just submitted an issue on to their github page...
