### ISSUE TITLE
error import pycairo in python3.6

### ISSUE THREAD

**Issue by timotito** [pygobject/pycairo#146]
pip install pycairo
Collecting pycairo
  Downloading https://files.pythonhosted.org/packages/48/20/5e83af98eb897935bf7dc39455e892ba866feebb9b7c3b392982866f9958/pycairo-1.18.1.tar.gz (200kB)
    100% |████████████████████████████████| 204kB 189kB/s 
Building wheels for collected packages: pycairo
  Running setup.py bdist_wheel for pycairo ... error
  Complete output from command /home/pytcom/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-teeogjag/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-3t63x6tp --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/cairo
  copying cairo/__init__.py -> build/lib.linux-x86_64-3.7/cairo
  copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.7/cairo
  copying cairo/py.typed -> build/lib.linux-x86_64-3.7/cairo
  running build_ext
  'pkg-config' not found.
  Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']
  
  ----------------------------------------
  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pycairo
Installing collected packages: pycairo
  Running setup.py install for pycairo ... error
    Complete output from command /home/pytcom/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-teeogjag/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ogmj96xe/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-3.7/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.7/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-3.7/cairo
    running build_ext
    'pkg-config' not found.
    Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']
    
    ----------------------------------------
Command "/home/pytcom/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-teeogjag/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ogmj96xe/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-teeogjag/pycairo/

**Comment by lazka** [comment]
Does following the steps in https://pycairo.readthedocs.io/en/latest/getting_started.html help?

**Comment by timotito** [comment]
Done !! 
But i got an other error import gi !!
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
Any helps ?!

**Comment by lazka** [comment]
That would be https://anaconda.org/conda-forge/pygobject (but I never used anaconda, so not sure)
