### ISSUE TITLE
pip install after installing cairo lib with vcpkg doesn't go straight

### ISSUE THREAD

**Issue by raffam** [pygobject/pycairo#149]
I have used `vcpkg` to install the gtk libraries, which include cairo as dependencies, so I run
`vcpkg install gtk:x86-windows`
and then I run
`vcpkg install integrate`
which supposedly should have Visual Studio locate the include files and the lib files of the newly installed library.
Nevertheless by running
`pip install pycairo`
It was unable to find `cairo.h`
I had to include the directory of the include files and of the library files of `vcpkg` directly. So I run
`set INCLUDE=<vckpg_dir>/installed/include`
`set LIB=<vckpg_dir>/installed/lib`
and then it worked

Supposedly `vcpkg install integrate` should have done that for me?

**Comment by lazka** [comment]
Yeah, see https://github.com/pygobject/pycairo/blob/7c3a71d1dee13cf3da729ef4c06673a2adc53ccc/setup.py#L470

Ideas to improve that welcome.

**Comment by lazka** [comment]
Would it have helped if we error out with a helpful message if INCLUDE/LIB isn't set for example?
