### ISSUE TITLE
Python2.7 install error

### ISSUE THREAD

**Issue by LiamMahoney** [pygobject/pycairo#150]
I'm trying to install pycairo on python 2.7.5 (CENTOS 7) and it is failing to install which is causing other packages that depend on it to fail (pygobject).

Any help with the error would be greatly appreciated. 
cairo version is 1.15.12 (came from the CentOS 7 EPEL repository)

```
pip install pycairo --no-cache-dir
Collecting pycairo
Downloading https://files.pythonhosted.org/packages/48/20/5e83af98eb897935bf7dc39455e892ba866feebb9b7c3b392982866f9958/pycairo-1.18.1.tar.gz (200kB)
Installing collected packages: pycairo
  Running setup.py install for pycairo ... error

 ERROR: Complete output from command /usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-W_2fzS/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m2gmT6/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-2.7/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-2.7/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-2.7/cairo
    running build_ext
    error: No such file or directory
    ----------------------------------------
ERROR: Command "/usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-W_2fzS/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m2gmT6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-W_2fzS/pycairo/
```

**Comment by lazka** [comment]
The output is sadly not that helpful. Do you have the `pkg-config` command installed?

**Comment by lazka** [comment]
You might get better errors when cloning this repo and running `python2 setup.py build`

**Comment by pedralho** [comment]
> You might get better errors when cloning this repo and running `python2 setup.py build`

pycairo git:(master) python --version
Python 2.7.10

pycairo git:(master) python setup.py build 
running build
running build_py
creating build
creating build/lib.macosx-10.14-intel-2.7
creating build/lib.macosx-10.14-intel-2.7/cairo
copying cairo/__init__.py -> build/lib.macosx-10.14-intel-2.7/cairo
copying cairo/__init__.pyi -> build/lib.macosx-10.14-intel-2.7/cairo
copying cairo/py.typed -> build/lib.macosx-10.14-intel-2.7/cairo
running build_ext
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1

**Comment by lazka** [comment]
@pedralho brew on CENTOS 7?
