### ISSUE TITLE
How to install mtools in windows 10

### ISSUE THREAD

**Issue by yogeshtj889** [pygobject/pycairo#151]
I am first time installing mtools on window using python.

I am using cmd for installing mtools "pip install mtools[all]".

It is giving error so I installed mtools in some parts as below,
1.pip install mtools[mlogfilter]
2.pip install mtools[mloginfo]

these two got installed but while installing **mplotqueries** as per brelow
3.pip install mtools[**mplotqueries**]
given error as below,

**D:\mongodb>pip install mtools[mplotqueries]
Requirement already satisfied: mtools[mplotqueries] in c:\program files\python37\lib\site-packages (1.5.3)
Requirement already satisfied: six in c:\program files\python37\lib\site-packages (from mtools[mplotqueries]) (1.12.0)
Requirement already satisfied: python-dateutil==2.7 in c:\program files\python37\lib\site-packages (from mtools[mplotqueries]) (2.7.0)
Collecting matplotlib==1.4.3 (from mtools[mplotqueries])
  Using cached https://files.pythonhosted.org/packages/bb/ac/485df0ecb15aa6fec1991945dc0cabfeb724a64f6729e34bab3c6a766813/matplotlib-1.4.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [1.4.3]
                    python: yes [3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019,
                            22:22:05) [MSC v.1916 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.14.5]
                       six: yes [using six version 1.12.0]
                  dateutil: yes [using dateutil version 2.7.0]
                      pytz: yes [using pytz version 2019.1]
                   tornado: yes [using tornado version 3.2.1]
                 pyparsing: yes [using pyparsing version 2.4.0]
                     pycxx: yes [Official versions of PyCXX are not compatible
                            with matplotlib on Python 3.x, since they lack
                            support for the buffer object.  Using local copy]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: yes [nose 0.11.1 or later is required to run the
                            matplotlib test suite.  pip/easy_install may attempt
                            to install it after matplotlib. / using
                            unittest.mock]
            toolkits_tests: yes [nose 0.11.1 or later is required to run the
                            matplotlib test suite.  pip/easy_install may attempt
                            to install it after matplotlib. / using
                            unittest.mock]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PyQt5 not found]
                    qt4agg: no  [PyQt4 not found]
                    pyside: no  [PySide not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: no  [The C/C++ header for Tk (tk.h) could not be
                            found.  You may need to install the development
                            package.]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing, installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-kfokd2ty\matplotlib\

D:\mongodb>**

Can any one give solution...

**Comment by lazka** [comment]
Best to ask the mtools developers.

**Comment by yogeshtj889** [comment]
Hi Lazka,

It is sticking while installing matplotlib, will you help me by telling me how to install whole matplotlib in windows using pip....

**Comment by lazka** [comment]
This is not pycairo related, so I can't help you, sorry.

Ask here: https://github.com/rueckstiess/mtools

**Comment by yogeshtj889** [comment]
Thanks
