### ISSUE TITLE
PDFSurface fails with file object.

### ISSUE THREAD

**Issue by hrittich** [pygobject/pycairo#153]
Consider the following code:

    import cairo
    fp = open('out.pdf', 'w')
    s = cairo.PDFSurface(fp, 400, 400)
    s.finish()

It fails with this error message:

    Traceback (most recent call last):
      File "issue.py", line 4, in <module>
        s.finish()
    __main__.IOError: error while writing to output stream

I would expect this code to produce the PDF file `out.pdf`. Replacing the file object by the file path works. Could you figure out, what causes this problem?

**Comment by lazka** [comment]
You need to open the file in binary mode ("wb")

**Comment by hrittich** [comment]
I see. It works. I have created a PR to improve the documentation and the error message.
