### ISSUE TITLE
Text rendering problem

### ISSUE THREAD

**Issue by xy-23** [pygobject/pycairo#155]
I try to use pycairo to render some Bengali text.
But the result is different from my expectation.

Environment: Windows 10 & python 3.7.3

```
import cairo

surface = cairo.SVGSurface('temp.svg', 300, 400)
context = cairo.Context(surface)
context.set_font_size(40)
context.move_to(50, 50)
context.select_font_face('Nirmala UI')
context.show_text('কি করিছস')
```

Result
<img width="188" alt="wrong" src="https://user-images.githubusercontent.com/47266984/66201812-becce680-e6d6-11e9-89c1-eff2a3d8244c.PNG">
The result is different from the input কি করিছস

Is there any way or param to fix this problem?

**Comment by lazka** [comment]
I don't know much about fonts, so please ask cairo: https://gitlab.freedesktop.org/cairo/cairo

Note that the docs for `show_text()` state:

> Note: The show_text() function call is part of what the cairo designers call the “toy” text API. It is convenient for short demos and simple programs, but it is not expected to be adequate for serious text-using applications. See show_glyphs() for the “real” text display API in cairo.

That could be the problem.

**Comment by xy-23** [comment]
```
import cairo

surface = cairo.SVGSurface('temp.svg', 500, 500)

context = cairo.Context(surface)

mat = cairo.Matrix(xx=10, yy=10)

fontface = cairo.ToyFontFace('Nirmala UI')
fontopt = cairo.FontOptions()

sfont = cairo.ScaledFont(fontface, mat, mat, fontopt)

context.show_text_glyphs('কি করছিস', *sfont.text_to_glyphs(50, 50, 'কি করছিস'))
```
I tried this but still wrong
<img width="158" alt="wrong" src="https://user-images.githubusercontent.com/47266984/66212854-3c055500-e6f1-11e9-811a-fd501b4e8367.PNG">

Could you please tell me more about how to use pango in  pycairo?

**Comment by lazka** [comment]
here is an example from a random github search: https://github.com/jerinphilip/seq2seq-ocr/blob/f0bc38a992f0fdb04f85252680e704b9e1b1a0ce/s2s_ocr/synthesis/font_image_renderer.py

**Comment by ldo** [comment]
Indic scripts need mandatory contextual forms. OpenType fonts will include the necessary substitution/placement rules, but Cairo on its own cannot cope with these: you need a text-shaping library like HarfBuzz to handle the layout correctly.

[Here](https://github.com/ldo/harfpy_examples/blob/master/indic-snippets) is an example script using my Python binding for HarfBuzz, and [here](https://www.deviantart.com/default-cube/art/Indic-Snippets-712198766) is the output from that example.

**Comment by stuaxo** [comment]
This sounds like good info for the docs.
