### ISSUE TITLE
Azure pipeline: Eventually remove PY_IGNORE_IMPORTMISMATCH=1

### ISSUE THREAD

**Issue by stuaxo** [pygobject/pycairo#167]
This to track the upstream bug in pytest so that we can remove  `PY_IGNORE_IMPORTMISMATCH=1` if it gets fixed there.

https://github.com/pytest-dev/pytest/issues/6303

**Comment by lazka** [comment]
TBH I think this might be a msys2/Python bug where we normalize paths to "/", but in 3.8 some things might have changed so we don't normalize in all places anymore and you get mismatches.

**Comment by stuaxo** [comment]
I don't know the test suite here that well, does the normalization happen at the pycairo-test end ?

**Comment by lazka** [comment]
It happens in Python itself. CPython is heavily patched in msys2 so it can be build with GCC and uses forward slashes as separators.
