### ISSUE TITLE
Wrong type in documentation for set_dash

### ISSUE THREAD

**Issue by turepalsson** [pygobject/pycairo#171]
The reference in context.rst states that the 'offset' parameter to set_dash is an int. If I am not mistaken, it is actually a float.

**Comment by lazka** [comment]
Thanks, yes, should be a float. Also in the type hints: https://github.com/pygobject/pycairo/blob/1ad3dc2f56459dd98bb5a64d5ebe6173d1c95b1e/cairo/__init__.pyi#L475
