### ISSUE TITLE
Pygame demo raises pygame.error: Unknown pixel format

### ISSUE THREAD

**Issue by carlosgmartin** [pygobject/pycairo#177]
Running [the pygame demo](https://pycairo.readthedocs.io/en/latest/integration.html#pygame-imagesurface) raises `pygame.error: Unknown pixel format`. It seems to work if `"ARGB"` is changed to `"RGBA"` but then the channels are in the wrong order. Adding [a new format](https://www.cairographics.org/documentation/pycairo/3/reference/constants.html#cairo-format) `cairo.FORMAT_RGBA32` would allow pycairo to interface correctly with pygame.

**Comment by lazka** [comment]
It works here. Any idea what could be different? pygame version, operating system, processor?

**Comment by carlosgmartin** [comment]
@lazka I have pygame version `2.0.0.dev4` and pycairo version `1.19.1` and am running on macOS Catalina version 10.15.3.

**Comment by lazka** [comment]
Thanks, I can reproduce with pygame 2.0.0.dev6

**Comment by lazka** [comment]
@carlosgmartin From what I see this shouldn't have changed in pygame. Can you report it to pygame and mention this issue?

**Comment by carlosgmartin** [comment]
@lazka [Done.](https://github.com/pygame/pygame/issues/1599)

**Comment by lazka** [comment]
Thanks :)

**Comment by lazka** [comment]
Confirmed to be a pygame issue in https://github.com/pygame/pygame/issues/1599#issuecomment-599955015 so I'm closing this.

Thanks for the report!
