### ISSUE TITLE
Import Error in a jupyter notebook

### ISSUE THREAD

**Issue by kolibril13** [pygobject/pycairo#178]
After using `pip install pycairo` in the first cell, then restating the notebook, I get the following message:

> ImportError: /opt/conda/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_svg_surface_set_document_unit

Here a screenshot.
![123](https://user-images.githubusercontent.com/44469195/77154105-5498da00-6a9b-11ea-992c-99b91eaf58da.png)

Any ideas? :)
Thanks a lot!

I just had the idea of a collaborative notebook, then we can try to get it to run together.
You can find it here:
https://colab.research.google.com/drive/1OkcTp6tW3oo_A5rQ3aKJJ7844DTer5Px

**Comment by lazka** [comment]
It means you are using a newer pycairo with an older cairo.

**Comment by kolibril13** [comment]
so, is there any option for me to use pycairo in a jupyter notebook then?
e.g. in the cooaborative notebook?

**Comment by kolibril13** [comment]
Actually, I managed to get it working on a local notebook, but it would be nice to also be able to do this on a remote notebook.
Further, would it be possible to write a function, that checks for the version, of cairo when it starts?

**Comment by stuaxo** [comment]
Hi,
   Along with @fomightez  I experimented a bit with a jupyter extension to output surfaces and images (it just renders them to pngs)

You may want to try it:
https://github.com/stuaxo/cairo-jupyter
(this version has a couple of fixes not in the fomightez branch yet)

Is there some info on what a remote notebook or one used for collaboration is ?   I used notebooks for prototyping all sorts of things, but have never used them collaboratively.

Without some changes to cairo itself I think the best that could be done right now is a more informative error message.

**Comment by kolibril13** [comment]
Oh nice, this ( https://github.com/stuaxo/cairo-jupyter ) is really great work!!
I just came up with a similar idea, see https://github.com/pygobject/pycairo/issues/180
I could actually make a pull to your repo  with these examples ;)

And one more thing that you might to try:
its a jupyter notebook that enables animations with manim.
Thats a repo that is based on cairo, but allows animations as well!
https://github.com/krassowski/jupyter-manim 

Back to my online notebook.
There it does not run.
The exact output of my remote notebook is:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-381c76bbfa70> in <module>
----> 1 import cairo

/opt/conda/lib/python3.7/site-packages/cairo/__init__.py in <module>
----> 1 from ._cairo import *  # noqa: F401,F403
      2 
      3 
      4 def get_include():
      5     """Returns a path to the directory containing the C header files"""

ImportError: /opt/conda/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_svg_surface_set_document_unit
```
But as I got it to work offline, it is not super important to fix this.

**Comment by stuaxo** [comment]
I'm up for PRs, part of the reason I got fomightez to support it was because I didn't have time myself, but he seems busy at the moment.

The animation stuff is interesting, I'll need to play with it.

For my notebook thing to be properly useful it would need to provide more tools than just rendering surfaces + contexts, e.g. maybe a cell magic that gives you information about the position of points on a path, or just something basic like display a grid of coordinates over whats rendered.

**Comment by fomightez** [comment]
This is good news. 

Sorry, I cannot help more. Part of it is that I cannot do most the advanced stuff necessary. I'm happy to help make things work on MyBinder.org since usually I can manage that.

**Comment by stuaxo** [comment]
That's cool :)

I'm happy to keep the repo on your side, as I don't have enough time to run it.   

BTW, there's a PR active which should make installing it a lot easier.

**Comment by stuaxo** [comment]
So @kolibril13 maybe put PRs against the repo fomightez has, and I can test them.

**Comment by fomightez** [comment]
Merged.

**Comment by fomightez** [comment]
Just checked and that version even works in JupyterLab 1.2.6 https://github.com/fomightez/cairo-jupyter .

**Comment by stuaxo** [comment]
@kolibril13 it seems like your issue was sorted, can we close this ?

**Comment by kolibril13** [comment]
yes
