### ISSUE TITLE
Pycairo error, despite installed correctly

### ISSUE THREAD

**Issue by diyarfaraj** [pygobject/pycairo#179]
I have cloned a repo from github and I want to run it locally. Now one of the required packages is PYCAIRO.

I have downloaded and installed Pycairo from this source: https://www.lfd.uci.edu/~gohlke/pythonlibs/ without any errors. 
The requirement.txt looks like this:

doit == 0.31.1

pyyaml == 5.1

jsonschema == 3.0.1

aiohttp == 3.5.4

flake8 == 3.7.7

pycairo == 1.18.0

wheel == 0.33.1

Now when I try to pip install "repo-name", All the other packages get installed correctly except Paycairo, I still get the following error:

`  e
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pycairo
Installing collected packages: pycairo, opcut
  Found existing installation: pycairo 1.19.1
    Uninstalling pycairo-1.19.1:
      Successfully uninstalled pycairo-1.19.1
  Running setup.py install for pycairo ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\microsoft visual studio\shared\python37_64\python.exe' -u -c 'import sys, setuptools, 
tokenize; sys.argv[0] = '"'"'C:\\Users\\USER~1\\AppData\\Local\\Temp\\pip-install-jvbafcg1\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER~1\\AppData\\Local\\Temp\\pip-install-jvbafcg1\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER~1\AppData\Local\Temp\pip-record-6zzxm18a\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\USER~1\AppData\Local\Temp\pip-install-jvbafcg1\pycairo\
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.py -> build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.pyi -> build\lib.win-amd64-3.7\cairo
    copying cairo\py.typed -> build\lib.win-amd64-3.7\cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\cairo
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=18 -DPYCAIRO_VERSION_MICRO=1 "-Ic:\program files (x86)\microsoft visual studio\shared\python37_64\include" "-Ic:\program files (x86)\microsoft visual studio\shared\python37_64\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tccairo/device.c /Fobuild\temp.win-amd64-3.7\Release\cairo/device.obj
    device.c
    C:\Users\User\AppData\Local\Temp\pip-install-jvbafcg1\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
  Rolling back uninstall of pycairo
  Moving to c:\users\user\appdata\roaming\python\python37\site-packages\cairo\
   from c:\users\user\appdata\roaming\python\python37\site-packages\~airo
  Moving to c:\users\user\appdata\roaming\python\python37\site-packages\pycairo-1.19.1.dist-info\
   from c:\users\user\appdata\roaming\python\python37\site-packages\~ycairo-1.19.1.dist-info
ERROR: Command errored out with exit status 1: 'c:\program files (x86)\microsoft visual studio\shared\python37_64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER~1\\AppData\\Local\\Temp\\pip-install-jvbafcg1\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER~1\\AppData\\Local\\Temp\\pip-install-jvbafcg1\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER~1\AppData\Local\Temp\pip-record-6zzxm18a\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.`

**Comment by stuaxo** [comment]
That version is externally maintained. 
Pycairo 1.20 has been released which comes with a WHL, try installing it and see if it gets any further.

**Comment by diyarfaraj** [comment]
@stuaxo  thanks! 
I will look into it, thanks!

**Comment by lazka** [comment]
As stated above, this should be fixed since 1.20
