### ISSUE TITLE
Cairo Module Not Found despite installing dependencies

### ISSUE THREAD

**Issue by kkin1995** [pygobject/pycairo#185]
Hi, I installed cairo using the command

`brew install cairo`

and pycairo and cairo-pkg config using

`pip3 install pycairo`
`brew install cairo pkg-config`

However, when I try to import cairo from the python interpretor, I get the following error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cairo'`

Any ideas how to resolve this?

**Comment by lazka** [comment]
Sorry for the late response.

That likely means "pip3 install pycairo" didn't succeed. We'd need an error message for why it failed.
