### ISSUE TITLE
PyObject_AsWriteBuffer is removed from CPython in 3.10

### ISSUE THREAD

**Issue by tacaswell** [pygobject/pycairo#190]
See https://github.com/python/cpython/blob/e4f1fe6edb216e04da03ae80b462ca273f00255b/Doc/whatsnew/3.10.rst#removed-1

It looks like PyObject_AsWriteBuffer is currently a wrapper around the new API (https://docs.python.org/3/c-api/objbuffer.html?highlight=pyobject_aswritebuffer#c.PyObject_AsWriteBuffer).

It looks like pycairo uses this function in one place (and wraps it to suppress the deprecation warnings) https://github.com/pygobject/pycairo/blob/f0c0e5a311968e993dc4911f7dbc9acc1b23009a/cairo/surface.c#L823-L825

Unfortunately I do not have time right now to dig into this and offer a fix.

**Comment by lazka** [comment]
3.10 will become an issue once it hits beta 2021-05-03 (https://www.python.org/dev/peps/pep-0619/) so not that pressing. But thanks for bringing it up!

My first try would be to just see what PyObject_AsWriteBuffer does internally and see it it's viable to replicate that.

**Comment by sarnold** [comment]
This is hitting me now in travis-ci in the Python: nightly build.  Hopefully I will notice the github notifies later...

**Comment by lazka** [comment]
ok, if it affects people today we should try to look into it.

**Comment by lazka** [comment]
PyObject_AsWriteBuffer is gone in master, PyObject_AsReadBuffer still needs to be removed.
