### ISSUE TITLE
Issue with pycairo while installing pygobject with python3.6 in Raspberry Pi 3

### ISSUE THREAD

**Issue by yatri-engineering** [pygobject/pycairo#219]
I've manually installed Python3.6 in Raspberry Pi3. I'm trying to install PyGObject which fails with the error:
```
ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.6 /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-f4i084p_/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools wheel pycairo
       cwd: None
  Complete output (36 lines):
  Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
  Collecting setuptools
    Downloading setuptools-50.3.2-py3-none-any.whl (785 kB)
  Collecting wheel
    Downloading wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting pycairo
    Downloading pycairo-1.20.0.tar.gz (344 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Building wheels for collected packages: pycairo
    Building wheel for pycairo (PEP 517): started
    Building wheel for pycairo (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.6 /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpazwu2ueb
         cwd: /tmp/pip-install-k30bx276/pycairo
    Complete output (12 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.6
    creating build/lib.linux-armv7l-3.6/cairo
    copying cairo/__init__.py -> build/lib.linux-armv7l-3.6/cairo
    copying cairo/__init__.pyi -> build/lib.linux-armv7l-3.6/cairo
    copying cairo/py.typed -> build/lib.linux-armv7l-3.6/cairo
    running build_ext
    Requested 'cairo >= 1.15.10' but version of cairo is 1.14.8
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
    ----------------------------------------
    ERROR: Failed building wheel for pycairo
  Failed to build pycairo
  ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.6 /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-f4i084p_/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools wheel pycairo Check the logs for full command output.
```
As per my understanding, the failure occurs while building PyCairo-1.20.0 which needs cairo >= 1.15.10' but version of cairo is 1.14.8.

**Possible solution:**
pycairo-1.20.0 is a recent release (5 Oct 2020). If the build uses pycairo-1.19.1, I believe the installation will succeed as it needs cairo >= 1.13.1.

**So, my question is:**

1. Disregarding my "possible solution", is there any way to install PyGObject using pip3 for python3.6 in Raspberry Pi 3?
2. With respect to my "possible solution", how to install PyGObject that uses PyCairo-1.19.1 ?

**Comment by lazka** [comment]
tricky..

`pip install --no-build-isolation pycairo==1.19.1 pygobject` might work.

I dropped support for 1.14.8 since debian stretch which raspberrypi uses is EOL.

**Comment by yatri-engineering** [comment]
The actual command I have to use is:
`sudo pip3 install --no-build-isolation pycairo==1.19.1 pygobject`

which gives another error:
```
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.6 /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp27ld_z7e
         cwd: /tmp/pip-install-e5aits86/pygobject
    Complete output (10 lines):
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 124, in prepare_metadata_for_build_wheel
        backend = _build_backend()
      File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
        obj = getattr(obj, path_part)
    AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.6 /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp27ld_z7e Check the logs for full command output.
```
which I believe is due to the flag --no-build-isolation .

I tried this as well:
`sudo PYGOBJECT_WITHOUT_PYCAIRO=1 pip3 install --no-build-isolation pygobject`

which gives the same error.

**Comment by lazka** [comment]
> which I believe is due to the flag --no-build-isolation .

yeah, I think it requires that you have an up-to-date setuptools installed. Maybe try in a venv.

>  `sudo PYGOBJECT_WITHOUT_PYCAIRO=1 pip3 install --no-build-isolation pygobject`

PYGOBJECT_WITHOUT_PYCAIRO no longer works with the way pip handles build dependencies nowadays.

**Comment by lazka** [comment]
I guess the best thing to do would be to release "1.20.1" which only requires cairo "1.14.8". I'll look into it.

**Comment by yatri-engineering** [comment]
@lazka 
That would be the best of the solutions.

Meanwhile an update:
I need PyGObject for bluez and I believe does not need pycairo.

Following a suggestion from this link,
https://github.com/pypa/pip/issues/6264

I am able to solve the issue.

The command I executed is:
`sudo PYGOBJECT_WITHOUT_PYCAIRO=1 pip3 install --no-build-isolation --no-use-pep517 pygobject`

Currently, I'm able to run the target bluez program. I'll look if it causes any other issues.

**Comment by stuaxo** [comment]
> I dropped support for cairo 1.14.8 since debian stretch which raspberrypi uses is EOL.

Looks like they may have moded to buster ?
https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/

Not sure if it changes the cairo version though.

**Comment by yatri-engineering** [comment]
> > I dropped support for cairo 1.14.8 since debian stretch which raspberrypi uses is EOL.
> 
> Looks like they may have moded to buster ?
> https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/
> 
> Not sure if it changes the cairo version though.

I am using a Raspberry Pi Computer Module 3 and it does not work with Buster yet.
The solution here is to either specify the version of PyCairo or exclude it while installing PyGObject.
