### ISSUE TITLE
issue with apple silicon while importing cairo

### ISSUE THREAD

**Issue by iamgigahex** [pygobject/pycairo#227]
Mac os version: 11.2.1
python: 3.7
while importing cairo getting this error
`Traceback (most recent call last):
  File "cairo_test.py", line 1, in <module>
    import cairo
  File "/Users/masafi/works/venvs/testenv-py3/lib/python3.7/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: dlopen(/Users/masafi/works/venvs/testenv-py3/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-darwin.so, 2): Symbol not found: _cairo_append_path
  Referenced from: /Users/masafi/works/venvs/testenv-py3/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/masafi/works/venvs/testenv-py3/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-darwin.so`

**Comment by naveen521kk** [comment]
Have a look at #226

**Comment by naveen521kk** [comment]
@iamgigahex if it is fixed can you close this issue?
