### ISSUE TITLE
Endian issue with the two numpy examples isurface_create_for_data2 and isurface_get_data

### ISSUE THREAD

**Issue by HinTak** [pygobject/pycairo#23]
Both of the examples assume small endian platforms. Cairo surface byte order is host order, whereas the two examples copy to/from numpy arrays in the small endian way.

**Comment by HinTak** [comment]
Here is an example of how to do the endianess correctly - use a uint32 dtype, and let the computer decide which way to go:
https://github.com/HinTak/freetype-py/commit/f7b8ce7f7f449005a1b3eff0e1407336515d1d5e

**Comment by lazka** [comment]
Thanks.

**Comment by lazka** [comment]
I've created #24, maybe you can have a quick look
