### ISSUE TITLE
Automatically format code with Black?

### ISSUE THREAD

**Issue by stuaxo** [pygobject/pycairo#237]
Would you accept a patch that formatted the code with Black and added linting for this on commit ?

It's possible to set up editors to do this on save, and to auto run the linting in poetry too, as seen here
https://cjolowicz.github.io/posts/hypermodern-python-03-linting/

(Other linters - like the one that sets import order are handy too).

**Comment by naveen521kk** [comment]
Hmm, black is for python files and I don't think this has much of python files?

**Comment by stuaxo** [comment]
I was thinking partly of the pyi file.. but just noticed black support isn't quite there to gob(had managed to forget how little python there is in pycairo).

Will close this :)
