### ISSUE TITLE
Test suite failure with typings and TeeSurface

### ISSUE THREAD

**Issue by pkgw** [pygobject/pycairo#238]
When building pycairo 1.20.1 in [the conda-forge packaging system][pr], we get build failures on a variety of platforms due to the typings test suite having an issue with TeeSurface:

[pr]: https://github.com/conda-forge/pycairo-feedstock/pull/26

```
=================================== FAILURES ===================================
_________________________________ test_typing __________________________________

    def test_typing():
[...]
        cairo_version = tuple(map(int, cairo.cairo_version_string().split(".")))
        if cairo_version >= (1, 16, 0):
>           assert collect_names(cairo) == collect_names(mod)
E           AssertionError: assert {'ANTIALIAS_B...AS_NONE', ...} == {'ANTIALIAS_B...AS_NONE', ...}
E             Extra items in the right set:
E             'TeeSurface'
E             'TeeSurface.add'
E             'TeeSurface.index'
E             'TeeSurface.remove'
E             Use -v to get the full diff
```

I think we'll try hacking around this by adding `TeeSurface` to the list of platform-dependent surfaces like `XlibSurface` that are ignored within this test, but I have no sense as to whether that's actually a good solution.

**Comment by naveen521kk** [comment]
Hmm, this would be fixed by enabling the optional tee backend in Cairo.

**Comment by lazka** [comment]
```
export PYTEST_ADDOPTS="-k 'not test_typing'"
```

would be a workaround
