### ISSUE TITLE
convert normal pdf to  cairo graphics format

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [pygobject/pycairo#244]
Hi,

I have a strange issue with my PDF's, I am using layout detection for  the PDF's by converting each PDF page to image and doing  inference on the image. one day I have split the document using **print to pdf** option from document viewer from GNOME desktop. When i check the properties of the converted file I get below. here you can see producer is cairo. but surprisingly, my  layout detection model is not working with any other  PDF's producers until i am converting original PDF to cairo specific as i said above (print to pdf using  document viewer from GNOME desktop). so is there anyway to change the pdf to cairo specific?
![cairo](https://user-images.githubusercontent.com/46083296/144283583-613eeec8-55f1-4ced-b65e-1be7d3c2a005.png)

**Comment by lazka** [comment]
I don't know how the "print to file" in GNOME is implemented, but as you noticed it likely uses libcairo in some way.

If your code can't handle certain PDF files, then that's not a cairo problem, and especially not a _pycairo_ problem.
