### ISSUE TITLE
BytesIO png to surface (cairo.IOError: error while reading from input stream)

### ISSUE THREAD

**Issue by maslaff** [pygobject/pycairo#245]
```
bytes = BytesIO()
# save png to BytesIO from PilImage
img.save(bytes, format='png')
imgsf = cairo.ImageSurface.create_from_png(bytes)
```

> cairo.IOError: error while reading from input stream

Through file normally work. E.g.:
```
img.save('img.png', format='png')
imgsf = cairo.ImageSurface.create_from_png('img.png')
```
>Ok

**Comment by dolfandringa** [comment]
I am fetching a png image online in a jupyter notebook and save it to io.BytesIO.
If I display it with in a jupyter notebook with
```
display(Image(background.getvalue(), width=width))
```
it shows up just fine, but if I 
```
surface=cairo.ImageSurface.create_from_png(background)
```
if shows me the same error. For some reason pycairo can not read from any file-like object.

**Comment by lazka** [comment]
You need to seek to where you want to read from first:

> bytes = BytesIO()
> # save png to BytesIO from PilImage
> img.save(bytes, format='png')

`bytes.seek(0)`

> imgsf = cairo.ImageSurface.create_from_png(bytes)

**Comment by maslaff** [comment]
> bytes.seek(0)

This is work! Thanks!
