### ISSUE TITLE
docs: mention freetype-py and show how to integrate it

### ISSUE THREAD

**Issue by lazka** [pygobject/pycairo#25]
Suggested in #24

**Comment by HinTak** [comment]
I have re-written all the ft-bitmap examples to do cairo surfaces. There are two examples which use ft-paths to draw on matplot, which I hope to rewrite, to do cairo paths.

**Comment by lazka** [comment]
There is now an "Integration with other Libraries" page in the docs: https://pycairo.readthedocs.io/en/latest/integration.html

Feel free to add something there.

**Comment by lazka** [comment]
I've just linked the examples folder for now. Feel free to expand it.
