### ISSUE TITLE
Expose `cairo_surface_write_to_png_stream` on `ImageSurface`

### ISSUE THREAD

**Issue by emdash** [pygobject/pycairo#259]
It seems a wrapper for this method is just missing.

https://www.cairographics.org/manual/cairo-PNG-Support.html#cairo-surface-write-to-png-stream

**Comment by emdash** [comment]
https://www.cairographics.org/manual/cairo-PNG-Support.html#cairo-surface-write-to-png-stream

**Comment by lazka** [comment]
[write_to_png()](https://pycairo.readthedocs.io/en/latest/reference/surfaces.html#cairo.Surface.write_to_png) also takes an open fileo bject (in binary mode) and uses `cairo_surface_write_to_png_stream` internally.

We could duplicate this though to avoid confusion.

**Comment by emdash** [comment]
Ah, okay this makes sense thanks.

**Comment by lazka** [comment]
> We could duplicate this though to avoid confusion.

I see that the docs for that function aren't very good, so on a second thought we should first improve that.
