### ISSUE TITLE
Add types for constants

### ISSUE THREAD

**Issue by lazka** [pygobject/pycairo#26]
Some thoughts:

*  cairo.OPERATOR_CLEAR should be an alias for cairo.Operator.CLEAR which should be a cairo.Operator
* cairo.Operator should be an int subclass
* it should pickle to int for compat
* it should have a nice repr
* I don't think there is a need to expose these in the C API

**Comment by lazka** [comment]
@stuaxo @HinTak any thoughts on this API addition/change? I've started something in #31

**Comment by HinTak** [comment]
Withdrawing constants is going to break existing code, which would make people unhappy. OTOH, I like the enums to be typed/classed. So I'd suggest adding a class but keep the old constants for compatibility.

**Comment by lazka** [comment]
There will be no API break with this. Thanks for the feedback.

**Comment by lazka** [comment]
There are some enum types where the value prefix doesn't match the type name:

cairo_path_data_type_t -> CAIRO_PATH_MOVE_TO

and some where the value name is not a valid Python attribute because they start with a digit:

PDF_VERSION_1_4, PS_LEVEL_2, SVG_VERSION_1_1

We should evaluate what other bindings do for those.

**Comment by lazka** [comment]
```
PHP:
    CairoSvgVersion.VERSION_1_1
Vala:
    Cairo.SvgVersion.VERSION_1_1
Ruby:
    Cairo::SVGVersion::VERSION_1_1
    Cairo::PathDataType::CLOSE_PATH
Mono:
    SvgVersion.OnePointOne
```

I'll go with the Ruby schema. uppercase SVG matches the surface class name.

**Comment by lazka** [comment]
https://pycairo.readthedocs.io/en/latest/reference/enums.html
