### ISSUE TITLE
Reference to cairocffi unclear

### ISSUE THREAD

**Issue by page200** [pygobject/pycairo#262]
An comma in the README [after a nonessential clause](https://www.merriam-webster.com/words-at-play/usage-of-essential-and-nonessential-clauses) might be missing, distorting the meaning. Without the comma, the [sentence syntax can be parsed](https://en.wikipedia.org/wiki/Parse_tree) as follows:

"If Pycairo is not what you need, have a look at [cairocffi](https://cairocffi.readthedocs.io/), which is an API compatible package using **{{{[cffi](https://cffi.readthedocs.io/) or [Qahirah](https://github.com/ldo/qahirah)}}}**, which is using [ctypes](https://docs.python.org/3/library/ctypes.html) and provides a more "pythonic" API with less focus on matching the cairo C API."

By adding a comma after "cffi":

"If Pycairo is not what you need, have a look at **{{{[cairocffi](https://cairocffi.readthedocs.io/), which is an API compatible package using [cffi](https://cffi.readthedocs.io/)}}},** _or_ **{{{[Qahirah](https://github.com/ldo/qahirah), which is using [ctypes](https://docs.python.org/3/library/ctypes.html) and provides a more "pythonic" API with less focus on matching the cairo C API.}}}**"

Is that what is meant? Better yet, make a bullet list of the alternatives.

Moreover, it is unclear what the pros and cons of using cffi are, i.e. the pros and cons of cairocffi. In what cases may Pycairo be "not what you need" as the README says, whereas cairocffi is?

Thanks!

**Comment by lazka** [comment]
> An comma in the README [after a nonessential clause](https://www.merriam-webster.com/words-at-play/usage-of-essential-and-nonessential-clauses) might be missing, distorting the meaning. Without the comma, the [sentence syntax can be parsed](https://en.wikipedia.org/wiki/Parse_tree) as follows:
> 
> "If Pycairo is not what you need, have a look at [cairocffi](https://cairocffi.readthedocs.io/), which is an API compatible package using **{{{[cffi](https://cffi.readthedocs.io/) or [Qahirah](https://github.com/ldo/qahirah)}}}**, which is using [ctypes](https://docs.python.org/3/library/ctypes.html) and provides a more "pythonic" API with less focus on matching the cairo C API."
> 
> By adding a comma after "cffi":
> 
> "If Pycairo is not what you need, have a look at **{{{[cairocffi](https://cairocffi.readthedocs.io/), which is an API compatible package using [cffi](https://cffi.readthedocs.io/)}}},** _or_ **{{{[Qahirah](https://github.com/ldo/qahirah), which is using [ctypes](https://docs.python.org/3/library/ctypes.html) and provides a more "pythonic" API with less focus on matching the cairo C API.}}}**"
> 
> Is that what is meant? Better yet, make a bullet list of the alternatives.

yes, thanks.

> Moreover, it is unclear what the pros and cons of using cffi are, i.e. the pros and cons of cairocffi. In what cases may Pycairo be "not what you need" as the README says, whereas cairocffi is?

Fair point. I didn't want to compare them too much back then as I was biased. I'll try to make this clearer.

**Comment by lazka** [comment]
I've moved the text to the bottom of https://pycairo.readthedocs.io/en/latest/ now and rewrote it.

Feedback welcome

**Comment by stuaxo** [comment]
Reads clearly to me, explains what it is + the benefits.  :+1:
