### ISSUE TITLE
Versioning scheme / are odd minors (e.g. 1.21.0) considered stable? 

### ISSUE THREAD

**Issue by marv** [pygobject/pycairo#267]
When proposing an update for pycairo to 1.21.0 on my distribution another developer raised the question whether pycairo follows a similar versioning scheme as cairo itselt with even minors being stable releases and odd minors being development versions. I couldn't really determine that, so I hope it's okay to ask here for clarification

Thanks in advance

**Comment by lazka** [comment]
pycairo is using semver since 1.11.0, so yes, 1.21.0 is stable

**Comment by lazka** [comment]
We had a note about this at some point, but I removed it in 320b22711fcc55b0158c15 because I assumed this question wouldn't come up anymore. I'll re-instate it.

**Comment by lazka** [comment]
see 494144aa38a
