### ISSUE TITLE
Phantom method: stroke_to_path?

### ISSUE THREAD

**Issue by nedbat** [pygobject/pycairo#275]
The [Context docs](https://pycairo.readthedocs.io/en/latest/reference/context.html#class-context) mention a method called `Context.stroke_to_path` in a few places, but it doesn't seem to exist?

**Comment by nedbat** [comment]
Hmm, from src/cairo.h:
```
/* XXX: NYI
cairo_public void
cairo_stroke_to_path (cairo_t *cr);
*/
```

**Comment by stuaxo** [comment]
NYI == not yet implemented ?

I wonder if it is still not yet implemented, and if so what needs doing ?

**Comment by nedbat** [comment]
Right, NYI is not yet implemented.  I have no idea what's required.  I think the best thing would be remove mention of it from PyCairo until cairo implements it.

**Comment by stuaxo** [comment]
I we sure it's not implented in Cairo itself ?

**Comment by nedbat** [comment]
The cairo.h fragment is from Cairo: https://github.com/freedesktop/cairo/blob/master/src/cairo.h#L915-L918

I've made https://github.com/pygobject/pycairo/pull/276 to remove the mentions.

**Comment by stuaxo** [comment]
Yep. just saw how it's in the cairo possible "student projects" part of their website.

Maybe upstream cairo would have have better luck trying to use a crowdfunding model for some of the unimplemented bits.

**Comment by stuaxo** [comment]
Change looks good to me.

**Comment by stuaxo** [comment]
Thanks @nedbat I spent the time to go through and read your changes properly, so felt happy to use my rarely-used merging ability on this one :)
