### ISSUE TITLE
Support for `CAIRO_FORMAT_RGB96F` and `CAIRO_FORMAT_RGBA128F`

### ISSUE THREAD

**Issue by page200** [pygobject/pycairo#288]
Cairo offers `CAIRO_FORMAT_RGB96F` and `CAIRO_FORMAT_RGBA128F` here:
https://gitlab.freedesktop.org/cairo/cairo/-/blob/8f1190dc825ad9ca805c39025dcbcb9aed8b496d/src/cairo.h#L410-411

Please support them in [cairo.Format](https://pycairo.readthedocs.io/en/latest/reference/enums.html#cairo.Format).

That would be crucial for an unbiased restrospective correction of [Cairo's incorrect treatment of sRGB](https://gitlab.freedesktop.org/cairo/cairo/-/issues/601).

**Comment by lazka** [comment]
Thanks, see #263

**Comment by Liquidmasl** [comment]
This does not seam to appear in cairo 1.23 when installing via pip in a docker container (base image python:3.9-slim).

This is a bit over my head and I am not sure if this is even the correct place to ask/tell this. sorry if not, am learning.

Host system; Windows 11, python 3.9

```
In [8]: cairo.version
Out[8]: '1.23.0'
In [9]: dir(cairo.Format)
Out[9]: 
['A1',
 'A8',
 'ARGB32',
 'INVALID',
 'RGB16_565',
 'RGB24',
 'RGB30',
 'RGB96F',
 'RGBA128F',... 
```

Container; base image: python:3.9-slim

```
>>> cairo.version
'1.23.0'
>>> dir(cairo.Format)
['A1', 'A8', 'ARGB32', 'INVALID', 'RGB16_565', 'RGB24', 'RGB30', '__abs__',...
 ```
