### ISSUE TITLE
PEP 517 build misses py3cairo.h and py3cairo.pc

### ISSUE THREAD

**Issue by mtelka** [pygobject/pycairo#312]
When I try PEP 517 build using [build-0.10.0](https://pypi.org/project/build/) there are missing two files when compared to legacy `setup.py` build: `/usr/include/pycairo/py3cairo.h` and `/usr/lib/pkgconfig/py3cairo.pc`.

**Comment by lazka** [comment]
Those files aren't supported with PEP517 builds and wheels as we don't know at wheel build time where things are going to be installed to and which prefix to include in the .pc files.

You need to use meson if you want system integration.
