### ISSUE TITLE
Pydroid 3 subprocess error

### ISSUE THREAD

**Issue by Nsifiok** [pygobject/pycairo#314]
I had an error arising from the subprocess on installation of pycairo on the pip of pydroid 3

**Comment by stuaxo** [comment]
Can you paste the error here ?

**Comment by Nsifiok** [comment]
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by Nsifiok** [comment]
The whole problem started from 'pip install pyobject' to run a tkinter code. This is part (beginning) of it: 
import tkinter as tk
from playsound import playsound

class RingtoneRadioButton(tk.Frame):
    def __init__(self, master=None, text="", value=None, ringtone=None, **kwargs):
        super().__init__(master, **kwargs)
        self.var = tk.StringVar(value=value)
        self.radio_button = tk.Radiobutton(self, text=text, var=self.var, value=value, bd=0, highlightthickness=0, \

**Comment by stuaxo** [comment]
I has a quick play with pydroid + the example.
It looks like the playsound library doesn't know about Android and it is treating it like Linux + expecting pygobject to work.

It may be worth opening a bug with the playsound library to support Pydroid on Android, in the meantime try using something else to play a sound, see this example - 
https://stackoverflow.com/questions/70600035/how-to-play-audio-on-pydroid3
