### ISSUE TITLE
Help Failed building wheel for pycairo

### ISSUE THREAD

**Issue by venkataraja705** [pygobject/pycairo#326]
**os: Ubunutu**
**python 3.10**

when i try to install pycairo in mu ubunutu machine 
i was getting error as the Building Wheel  Fail

**Issue:**

Collecting pycairo
  Using cached pycairo-1.24.0.tar.gz (344 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pycairo
  Building wheel for pycairo (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycairo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/cairo
      copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-310/cairo
      copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-310/cairo
      copying cairo/py.typed -> build/lib.linux-x86_64-cpython-310/cairo
      running build_ext
      'pkg-config' not found.
      Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycairo
Failed to build pycairo

**ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects**

**Comment by venkataraja705** [comment]
is the **pycairo** any support for the Linux distros?

**Comment by hs1white** [comment]
Your issue has the hint:    'pkg-config' not found.

Here are the docs: https://pycairo.readthedocs.io/en/latest/getting_started.html

For Ubuntu it says the reqs are: 

sudo apt install libcairo2-dev pkg-config python3-dev
