### ISSUE TITLE
Cairo Tutorial for Python (and other) Programmers link not exists?

### ISSUE THREAD

**Issue by jekoie** [pygobject/pycairo#327]
I try to learn it with python  pycairo, but the link [Cairo Tutorial for Python (and other) Programmers](http://www.tortall.net/mu/wiki/CairoTutorial) not exist,pleas add right link for python users.

**Comment by stuaxo** [comment]
It looks like the wiki there is down, I have sent a mail to the webmaster link on their main page.

**Comment by stuaxo** [comment]
@PeterJohnson is this something you can fix?

**Comment by PeterJohnson** [comment]
I'll take a look.

**Comment by jekoie** [comment]
It's important  to spread `pycairo`，It need complete documents and tutorial, althought it seems very simple.

**Comment by PeterJohnson** [comment]
The tutorial is now back online.

**Comment by stuaxo** [comment]
Lovely stuff, thanks @jekoie for finding this.
