### ISSUE TITLE
incorrect pkg-config file written for user-installed build

### ISSUE THREAD

**Issue by pdknsk** [pygobject/pycairo#34]
```Bash
$ python setup.py install -O2 --user
```
This makes file ```$HOME/.local/lib/pkgconfig/pycairo.pc``` with the following content.
```
prefix=None

Name: Pycairo
Description: Python 2 bindings for cairo
Version: 1.13.0
Requires: cairo
Cflags: -I${prefix}/include/pycairo
Libs:
```
Which does not work for obvious reasons.

**Comment by lazka** [comment]
Thanks.

**Comment by lazka** [comment]
Do you require a bugfix release, or can this wait for the next feature release?

**Comment by pdknsk** [comment]
(I already edited the file myself.)

**Comment by lazka** [comment]
ok. next release it is then.. or when we manage to get it on pypi
