### ISSUE TITLE
Memory leak in ImageSurface.get_data

### ISSUE THREAD

**Issue by minus7** [pygobject/pycairo#41]
When creating an ImageSurface in a loop and calling `get_data()` on it, memory leaks.
It's about 5KB in resident memory, shown by the mem function, and about 1MB of virtual memory, observable in htop, which is about the size of the surface.

Calling `get_data` in the loop on the same SurfaceImage does not allocate more memory.

```python
#!/usr/bin/env python3

import cairo
import resource

def mem():
    print("Memory usage: {:.0f}M".format(
        resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024))

mem()

for i in range(10000):
    s = cairo.ImageSurface(cairo.FORMAT_ARGB32, 500, 500)
    s.get_data()

mem()
#input()
```

I'm using Python 3.6.1 and the latest commit from master as well as 1.13.2+5+gcd6b840-1 (from the ArchLinux repos).

**Comment by minus7** [comment]
Seems like calling `s.finish()` frees the memory. Using `del s` does not seems to trigger that.

**Comment by lazka** [comment]
Thanks, confirmed.

**Comment by lazka** [comment]
get_data() creates a buffer with PyBuffer_FillInfo(), then a memoryview with PyMemoryView_FromBuffer(), but releasing the memoryview doesn't release the buffer. No idea why.

**Comment by lazka** [comment]
Let's ask upstream: https://bugs.python.org/issue30527

**Comment by lazka** [comment]
I'll release 1.13.3 with this tomorrow.

Thanks for the report!

**Comment by lazka** [comment]
New release is out: https://github.com/pygobject/pycairo/releases/tag/v1.13.3

https://pycairo.readthedocs.io/en/latest/changelog.html

**Comment by minus7** [comment]
Great! Thanks for the quick fix.

 As I understand it the BufferProxy would not have been necessary if the ImageSurface implemented the buffer interface directly, right? Why is a proxy object a better solution?

**Comment by lazka** [comment]
> As I understand it the BufferProxy would not have been necessary if the ImageSurface implemented the buffer interface directly, right?

Yes

> Why is a proxy object a better solution?

Fair question. I don't really know the ins and outs of the new extended buffer interface in python 3 and this allows me to control the memoryview creation a bit more by not directly allowing memoryview(surface).

There are some properties to change in the buffer interface setup, like item type, shape strides, some of which I think can't be changed later without breaking existing uses. My thinking was that maybe in the future we can add another method returning a memoryview containing a multi dimensional array of pixels + color components. Something like get_pixel_data()

Maybe that would have been possible either way..
