### ISSUE TITLE
Trying to install cairo's bindings to python

### ISSUE THREAD

**Issue by JUSTINTHONG** [pygobject/pycairo#63]
I obtain this error that certain files are not found. 

`justins-mbp:Downloads justinthong$ pip install pycairo-1.15.0.tar.gz 
Processing ./pycairo-1.15.0.tar.gz
    Complete output from command python setup.py egg_info:
    'pkg-config' not found.
    Command ['pkg-config', '--cflags-only-I', 'cairo']
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xb/n20n792n5zn0xpyhpdcn4chm0000gn/T/pip-QlD9gj-build/`

**Comment by lazka** [comment]
Yes, you need to have pkg-config and cairo installed

**Comment by lazka** [comment]
I assume you are on a mac? In case you use homebrew try "brew install python cairo"

**Comment by JUSTINTHONG** [comment]
I tried doing so but receive an error

'
==> Pouring python-2.7.13_1.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-2
Target /usr/local/bin/2to3-2
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-2'

To force the link and overwrite all conflicting files:
  brew link --overwrite python

To list all files that would be deleted:
  brew link --overwrite --dry-run python

Possible conflicting files are:
/usr/local/bin/2to3-2 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/2to3-2
/usr/local/bin/2to3-2.7 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/2to3-2.7
/usr/local/bin/idle2 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/idle2
/usr/local/bin/idle2.7 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/idle2.7
/usr/local/bin/pydoc2 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/pydoc2
/usr/local/bin/pydoc2.7 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/pydoc2.7
/usr/local/bin/python2 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
/usr/local/bin/python2-config -> /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
/usr/local/bin/python2.7 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
/usr/local/bin/python2.7-config -> /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
/usr/local/bin/pythonw2 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2
/usr/local/bin/pythonw2.7 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
/usr/local/bin/smtpd2.7.py -> /Library/Frameworks/Python.framework/Versions/2.7/bin/smtpd2.7.py
/usr/local/bin/smtpd2.py -> /Library/Frameworks/Python.framework/Versions/2.7/bin/smtpd2.py'

**Comment by lazka** [comment]
I don't have much macports/homebrew experience...

My guess would be that both systems are conflicting here, so you can either deinstall python in macports or execute the suggested command "brew link --overwrite python". But this might break your system, I don't know.

I'll try to add an macOS installation test on travis-ci to make sure that this works.

**Comment by lazka** [comment]
I've added the test run now and things seem to work with homebrew + virtualenv at least: https://travis-ci.org/pygobject/pycairo/jobs/257499673
