### ISSUE TITLE
Find the correct libdir in setup.py

### ISSUE THREAD

**Issue by orbea** [pygobject/pycairo#70]
OS: `Slackware64-current`

The 64 bit version of Slackware installs libraries to `/usr/lib64` while the 32 bit version uses `/usr/lib`. The problem is that in `setup.py` the library directory is hardcoded to `lib` and this results in the pkgconfig file being installed to the wrong directory in Slackware64.
```
libdir = os.path.join(self.install_data, "lib")
```
While other library files will be correctly installed to `/usr/lib64/python3.6/site-packages/` since python itself was configured to use that `lib64`. Can this be made so that it will use the same directory as the other library files as configured in python?

This commit for the six-library shows an example of how this is done, but I do not know python at all so I am having difficulty in implementing it. Any help would be appreciated, thanks!
https://github.com/ngageoint/six-library/commit/98f6397b6bf70f1cf8066342c6344316a2bd9ebf

**Comment by infirit** [comment]
Something like below would work I guess.

```python
>>> from distutils import sysconfig
>>> sysconfig.get_config_var("LIBDIR")
'/usr/lib64'
>>> sysconfig.get_config_var("LIBPC")
'/usr/lib64/pkgconfig'
```

**Comment by stuaxo** [comment]
That looks like it should work to me, (those values seem correct on Ubuntu Zesty 64 bit at least).

Any chance you could make a pull request with this change?   -that way the it will be tested by travis.

**Comment by infirit** [comment]
#71

**Comment by orbea** [comment]
Thank you, but unfortunately that doesn't seem to work here even if the values seem correct when I test them in a python 2 or 3 shell.

**Comment by stuaxo** [comment]
Hi @orbea,  which OS are you testing on ?

**Comment by orbea** [comment]
I am using Slackware64-current with python-3.6.2. I am able of testing python-2.7.13 also. Currently slackware is using an outdated version which still used waf and as a consequence did not have this issue, but I would like to see this fixed before I request for this to be updated so that newer pygobject packages can be more accessible.

**Comment by stuaxo** [comment]
I ran Slackware64-live which has python2.7.13 (I have no idea how to install python3 in slackware).

Can you paste the commands you are running and the output ?


One thing I noticed - "import cairo" doesn't seem to work inside the source directory after installation (this is possibly a bug).

Try changing to another directory and see if you ```python -c "import cairo"``` works.

**Comment by orbea** [comment]
Python3 can be compiled and installed from the Slackbuids.org repo.
https://slackbuilds.org/repository/14.2/python/python3/

1. `wget https://slackbuilds.org/slackbuilds/14.2/python/python3.tar.gz`
2. `tar xvf python3.tar.gz`
3. `cd python3`
4. `wget https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tar.xz`
5. `sh python3.SlackBuild`
6. `installpkg /tmp/python3-3.6.2-x86_64-1_SBo.tgz`

The current py3cairo build script is here.
https://slackbuilds.org/repository/14.2/python/py3cairo/

For the purposes of testing I have updated it here.
https://pastebin.com/B1xnb50U

You can repeat the process for python3 above to install it replacing the `py3cairo.SlackBuild` file with the above and placing the following link in the extracted slackbuild directory as `71.patch`.
https://patch-diff.githubusercontent.com/raw/pygobject/pycairo/pull/71.patch

1. `wget https://slackbuilds.org/slackbuilds/14.2/python/py3cairo.tar.gz`
2. `tar xvf py3cairo.tar.gz`
3. `cd py3cairo`
4. Replace `py3cairo.SlackBuild` with https://pastebin.com/B1xnb50U
5. `wget https://patch-diff.githubusercontent.com/raw/pygobject/pycairo/pull/71.patch`
6. `wget https://github.com/pygobject/pycairo/releases/download/v1.15.1/pycairo-1.15.1.tar.gz`
7. `sh p3cairo.SlackBuild`

The contents of the installed package can be viewed in the script output and in `/tmp/SBo/package-py3cairo/`. The current behavior of the patch seems to be that `install_pkgconfig` does nothing.

I tested `python -c "import cairo" and it seems to work as it returns `0`, but I do not see any output?

**Comment by infirit** [comment]
Can you try https://github.com/pygobject/pycairo/pull/71/commits/70ffec095caa8e6a1e52cb452534ecc64e9125d2

**Comment by lazka** [comment]
New release: https://github.com/pygobject/pycairo/releases/tag/v1.15.2

Please test

**Comment by orbea** [comment]
Thank you! I tested the new release with both python 2 and 3 in both 64 bit install and a 32 bit install and can confirm it works. As the change is already applied to the new release I will close this issue now. :)

**Comment by lazka** [comment]
Cool, thanks for testing!

**Comment by lazka** [comment]
This change broke things with jhbuild under fedora as that doesn't add lib64 to PKG_CONFIG_PATH.

@orbea would installing the file into /usr/share/pkgconfig work?

**Comment by lazka** [comment]
Or make jhbuild install python modules into the jhbuild libdir. I'll try that first.

**Comment by infirit** [comment]
Or add an option that folks can use, something like below?

```diff
diff --git a/setup.py b/setup.py
index b3d08d7..8081e71 100755
--- a/setup.py
+++ b/setup.py
@@ -101,13 +101,16 @@ class test_cmd(Command):
 
 class install_pkgconfig(Command):
     description = "install .pc file"
-    user_options = []
+    user_options = [
+        ("pkgconfigdir=", None, "Specify pkgconfig dir"),
+    ]
 
     def initialize_options(self):
         self.install_data = None
         self.install_base = None
         self.outfiles = []
         self.compiler_type = None
+        self.pkgconfigdir = None
 
     def finalize_options(self):
         self.set_undefined_options(
@@ -131,8 +134,11 @@ class install_pkgconfig(Command):
         if self.compiler_type == "msvc":
             return
 
-        python_lib = sysconfig.get_python_lib(True, True, self.install_data)
-        install_dir = os.path.join(os.path.dirname(python_lib), 'pkgconfig')
+        if self.pkgconfigdir:
+            install_dir = os.path.join(self.install_data, self.pkgconfigdir)
+        else:
+            python_lib = sysconfig.get_python_lib(True, True, self.install_data)
+            install_dir = os.path.join(os.path.dirname(python_lib), 'pkgconfig')
         self.mkpath(install_dir)
 
         if sys.version_info[0] == 3:
@@ -175,6 +181,7 @@ class build_ext(du_build_ext):
 
     user_options = du_build_ext.user_options + [
         ("enable-xpyb", None, "Build with xpyb support (default=disabled)"),
+        ("pkgconfigdir=", None, "Specify pkgconfig dir"),
     ]
 
     def initialize_options(self):
```

**Comment by orbea** [comment]
Honestly I would consider that a fedora bug.  That said Slackware does seem to minimally use `/usr/share/pkgconfig`, but I do not know how that differs from `/usr/lib/pkgconfig`?

**Comment by lazka** [comment]
@infirit Thanks, but I'd like this to just work as with other software ideally.

@orbea yeah, I think it's a jhbuild+fedora problem, I'll  try to fix it there.
