### ISSUE TITLE
py3cairo.h not included with latest version of pycairo

### ISSUE THREAD

**Issue by JoshuaPK** [pygobject/pycairo#82]
I am attempting to compile pygobject release 3.26.0.  It is breaking because it can't find the include files for py3cairo... even though I have installed the latest pycairo.  If I revert back to the latest version of pycairo that includes py3cairo.h, this is pycairo version 1.10.1.  Pygobject will not compile with pycairo 1.10.1, as it requires pycairo >= 1.11.

**Comment by infirit** [comment]
[setup.py creates it when it detects python3](https://github.com/pygobject/pycairo/blob/master/setup.py#L287). So you either have it in a place pygobject does not look or you have not build/installed pycairo for python3.

**Comment by lazka** [comment]
As @infirit said, make sure you use Python 3 when installing.

Please state your operating system and how you are trying to install both pygobject and pycairo.

**Comment by JoshuaPK** [comment]
Apparently, something is not picking up the PYCAIRO_CFLAGS and PYCAIRO_LIBS environment variables properly.  Starting from scratch, I get past the original error, and now compilation stops on pygi-foreign-cairo.c because it can't find the py3cairo.h file.  For some reason it is not picking up PYCAIRO_CFLAGS.  I need to continue going down that path- but for now this issue is closed.

For further reference in case someone else runs into a similar issue:

OS/Python: CentOS 7 with RedHat Software Collections Python 3.6

Environment is set up like this.  At the terminal:
1. scl enable rh-python36 bash
2. cd /home/josh/dev/tests
3. virtualenv cairotest
4. cd cairotest
5. . bin/activate
6. (Clones pycairo from GitHub; builds/installs pycairo using setup.py)
7. (Downloads and extracts pygobject-3.26.1.tar.xz)
8. export PYCAIRO_CFLAGS=-I/home/josh/dev/test/cairotest/include/pycairo
9. export PYCAIRO_LIBS=-L/home/josh/dev/tests/cairotest/lib64/python3.6/site-packages/cairo
10. cd pygobject-3.26.1
11. python ./setup.py build

**Comment by lazka** [comment]
Try `export PKG_CONFIG_PATH=/home/josh/dev/test/cairotest/share/pkgconfig`
