### ISSUE TITLE
Robust access to py3cairo.h

### ISSUE THREAD

**Issue by anntzer** [pygobject/pycairo#92]
Now that installs from wheels don't include pkg-config data anymore, but still include the py3cairo header, it would be useful to still have a way to include that header in a robust fashion (when py3cairo is installed from a wheel).  (Obviously we still need to include `pkg-config --cflags cairo` but that's not a problem.)

A few options include
- add a cairo.get_include() function, similarly to how numpy.get_include() does it.
- make sure that `pycairo/py3cairo.h` is always available from the default include path set by distutils when building an extension (even when in a venv), and document it as the new way to include the header (this is currently the case afaict, just not documented as such).

**Comment by lazka** [comment]
Yeah, that's something I've been struggling with in pygobject (https://gitlab.gnome.org/GNOME/pygobject/blob/94904a17fb65b5174aca58c9e8ed6ebd50bc6cb3/setup.py#L489) and still does not work everywhere :/

Can you explain what the second option would do?

**Comment by anntzer** [comment]
Basically, currently one can just do `#include <pycairo/py3cairo.h>` instead of `#include <py3cairo.h>` and then compile the extension with `$(pkg-config --cflags cairo)` and `$(pkg-config --libs cairo)`, because the directory that contains `pycairo/py3cairo.h` (*not* the directory that contains `py3cairo.h`) already happens to be added to the include path by distutils.

The idea is just to say that this is now the recommended method and document it as e.g. "to compile an extension that links against pycairo, include the header using `#include <pycairo/py3cairo.h>` and use cairo instead of pycairo in the pkg-config calls".

**Comment by lazka** [comment]
Thanks, I'll have a look.

**Comment by lazka** [comment]
Proposal:

* Include the header in the Python package, something like
  `"/usr/lib/python2.7/dist-packages/cairo/include/pycairo/pycairo.h"`
* Make the pkg-config point to it
* Add cairo.get_include()
* Install a header to the old location which just includes
  `#include "<relative-path-to-new-header>"`
  as I'm a bit worried that because it was in a standard location
  things might have hardcoded it.

Any thoughts?

**Comment by anntzer** [comment]
Well, the latest release already broke packages that were relying on pkg-config so I wouldn't worry to much about back compat and go for whatever is simplest/most robust...

**Comment by lazka** [comment]
ok, ignoring the back compat header, does the rest sound OK to you?

**Comment by anntzer** [comment]
I think that looks good.

**Comment by lazka** [comment]
ok, thanks. Sorry for the trouble, re pkg-config. I didn't think that anyone would depend on the wheel+pkgconfig use case.

**Comment by anntzer** [comment]
It's more like "I want to distribute sources of another package that depends on pycairo and I cannot control how the end user has installed pycairo to start with..."

**Comment by lazka** [comment]
I've started something in #96

**Comment by lazka** [comment]
It's in master now. I'll test it a bit before doing a new release.

**Comment by lazka** [comment]
Seems to work fine, I'll do a release now.

**Comment by anntzer** [comment]
thanks
