### ISSUE TITLE
debian issues

### ISSUE THREAD

**Issue by lazka** [pygobject/pycairo#98]
Debian pybuild has some problems with the new installation layout because it moves the files after installation, proposed fix:

* Install the header to /usr/include again
* The header in the package_data uses a relative include to /usr/include
* The .pc file again refers to /usr/include

This gets rid of relative paths containing "/dist-packages/python3.6/"... and the .pc file and header file are not containing python version information, so no conflicts with multiple py3 versions.

**Comment by lazka** [comment]
Switching the relative path doesn't work with pkg_resouces, so I've changed it to just install the header twice now.

**Comment by stuaxo** [comment]
Maybe if one of the headers was a symlink to the other it would be marginally cleaner ?

**Comment by lazka** [comment]
Doesn't work sadly, /usr/include -> /usr/lib breaks as the link includes the library directory name and this is changed by debian on install. The other way around breaks pkg_resources.resource_filename https://github.com/pygobject/pycairo/blob/master/cairo/__init__.py#L23

**Comment by stuaxo** [comment]
:( the Debian patches along with setuptools sandboxing seems like a nightmare, duplication definitely sounds like the easiest way to get it working.
